/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa.InterfacesSecundaria;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sistema_bancario.ConexionSistemaBancario;

/**
 *
 * @author Javier
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        setTitle("Nuevo Cliente");
        Telef(cedula_cliente);
        Rc(ruc);
        Telef(telefono_cliente);
        letras(nombre_cliente);
        letras(situacion_laboral);

    }

    public void letras(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    //getToolkit().beep();
                    e.consume();
                }
            }
        });
    }

    private int ct = 10;

    public void Telef(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    //getToolkit().beep();
                    e.consume();
                }
                if (a.getText().length() == ct) {
                    e.consume();
                }
            }
        });
    }

    public void numeros(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    //getToolkit().beep();
                    e.consume();
                }
            }
        });
    }

    private int rc = 13;

    public void Rc(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    //getToolkit().beep();
                    e.consume();
                }
                if (a.getText().length() == rc) {
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JButton();
        cedula_cliente = new javax.swing.JTextField();
        ruc = new javax.swing.JTextField();
        nombre_cliente = new javax.swing.JTextField();
        situacion_laboral = new javax.swing.JTextField();
        correo_cliente = new javax.swing.JTextField();
        telefono_cliente = new javax.swing.JTextField();
        direccion_cliente = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 2, 2, new java.awt.Color(0, 102, 102)));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Lucida Console", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("DATOS DEL CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 440, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cédula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ruc :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Completo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Situación Laboral");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 80, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Teléfono:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 90, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes_opt.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 130, 140));

        BotonBuscar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar-TuneaTaringa_opt.png"))); // NOI18N
        BotonBuscar.setBorder(null);
        BotonBuscar.setContentAreaFilled(false);
        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 160, 90));

        cedula_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cedula_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cedula_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 130, 20));

        ruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ruc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, 20));

        nombre_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, 20));

        situacion_laboral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        situacion_laboral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(situacion_laboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 380, 20));

        correo_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correo_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(correo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 170, 20));

        telefono_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(telefono_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 150, 20));

        direccion_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccion_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(direccion_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 20));

        BotonIngresar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        BotonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardar_opt.png"))); // NOI18N
        BotonIngresar.setBorder(null);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 140, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image55ef95555423e5_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        // TODO add your handling code here:

        ConexionSistemaBancario cn = new ConexionSistemaBancario().conectar();            // Conecta con la base de datos XE con el usuario system y la contraseña password
        Connection c = cn.getConexion();

        try {
            CallableStatement cst = c.prepareCall("{call PA_INSERTAR_CLIENTE (?,?,?,?,?,?,?)}");
            cst.setInt(1, Integer.parseInt(cedula_cliente.getText()));
            cst.setString(2, ruc.getText());
            cst.setString(3, nombre_cliente.getText());
            cst.setString(4, situacion_laboral.getText());
            cst.setString(5, direccion_cliente.getText());
            cst.setString(6, correo_cliente.getText());
            cst.setInt(7, Integer.parseInt(telefono_cliente.getText()));
            cst.execute();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        } finally {
            try {
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }

        cedula_cliente.setText("");
        ruc.setText("");
        nombre_cliente.setText("");
        situacion_laboral.setText("");
        direccion_cliente.setText("");
        correo_cliente.setText("");
        telefono_cliente.setText("");

        //JOptionPane.showMessageDialog(null, "La información se guardo con éxito!");                       

    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        ConexionSistemaBancario f = new ConexionSistemaBancario();
        f.conectar();

        int id = Integer.parseInt(cedula_cliente.getText());
        ResultSet resultado;

        try {
            resultado = f.consultar("SELECT ruc, nombre_cliente, situacion_laboral, direccion_cliente, correo_cliente, telefono_cliente FROM cliente "
                    + "WHERE cedula_cliente ='" + id + "'");
            while (resultado.next()) {
                String Rc = resultado.getString("ruc");
                String nombrecliente = resultado.getString("nombre_cliente");
                String situacionlaboral = resultado.getString("situacion_laboral");
                String direccioncliente = resultado.getString("direccion_cliente");
                String correocliente = resultado.getString("correo_cliente");
                int telefonocliente = resultado.getInt("telefono_cliente");

                ruc.setText("" + Rc);
                nombre_cliente.setText("" + nombrecliente);
                situacion_laboral.setText("" + situacionlaboral);
                direccion_cliente.setText("" + direccioncliente);
                correo_cliente.setText("" + correocliente);
                telefono_cliente.setText("" + telefonocliente);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de conexion con la base de datos");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JTextField cedula_cliente;
    private javax.swing.JTextField correo_cliente;
    private javax.swing.JTextField direccion_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre_cliente;
    private javax.swing.JTextField ruc;
    private javax.swing.JTextField situacion_laboral;
    private javax.swing.JTextField telefono_cliente;
    // End of variables declaration//GEN-END:variables
}
