/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa.InterfacesSecundaria;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sistema_bancario.ConexionSistemaBancario;

/**
 *
 * @author Javier
 */
public class Pago extends javax.swing.JFrame {
    ResultSet rs = null; 
    Statement stmt = null;    
    /**
     * Creates new form Pago
     */
    public Pago() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        setTitle("Pago");
        fecha_pago.setText(fecha());
        numeros(id_pago);
        numeros(numero_pres);
        numeros(numero_pago);
        numeros(capital_inicial);
        numeros(amortizacion_capital);
        numeros(interes_mensual);
        numeros(valor_cuota);
        numeros(valor_pagado);
    }
    
    public void numeros (JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if (!Character.isDigit(c)){
                    //getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
    
    public static String fecha(){
        Date fecha=new Date();
        SimpleDateFormat formatofecha=new SimpleDateFormat("dd-MM-YYYY");
        return formatofecha.format(fecha);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fecha_pago = new javax.swing.JTextField();
        id_pago = new javax.swing.JTextField();
        todo = new javax.swing.JButton();
        numero_pres = new javax.swing.JTextField();
        Limpiar = new javax.swing.JButton();
        numero_pago = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        amortizacion_capital = new javax.swing.JTextField();
        valor_cuota = new javax.swing.JTextField();
        capital_inicial = new javax.swing.JTextField();
        interes_mensual = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        valor_pagado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 30, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nº de Préstamo :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nº de Pago:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Capital Inicial:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Amortización:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Interés Mensual:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Fecha de Pago:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Valor de la Cuota:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Valor del Pago:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pago_opt.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 110, 110));

        fecha_pago.setBackground(new java.awt.Color(240, 240, 240));
        fecha_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha_pago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fecha_pago.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        fecha_pago.setEnabled(false);
        getContentPane().add(fecha_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 95, 140, 20));

        id_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_pago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(id_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 50, 30));

        todo.setBackground(new java.awt.Color(255, 255, 255));
        todo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        todo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papelera_opt.png"))); // NOI18N
        todo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        todo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        todo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoActionPerformed(evt);
            }
        });
        getContentPane().add(todo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 30, 40));

        numero_pres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numero_pres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(numero_pres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 165, 50, 30));

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_opt.png"))); // NOI18N
        Limpiar.setBorder(null);
        Limpiar.setContentAreaFilled(false);
        Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, 60));

        numero_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numero_pago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(numero_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 165, 50, 30));

        BotonBuscar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar-TuneaTaringa_opt.png"))); // NOI18N
        BotonBuscar.setBorder(null);
        BotonBuscar.setContentAreaFilled(false);
        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 130, 50));

        amortizacion_capital.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amortizacion_capital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(amortizacion_capital, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 160, 20));

        valor_cuota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_cuota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(valor_cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 20));

        capital_inicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        capital_inicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(capital_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 160, 20));

        interes_mensual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interes_mensual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(interes_mensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, 20));

        BotonIngresar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        BotonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardar_opt.png"))); // NOI18N
        BotonIngresar.setBorder(null);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 130, 40));

        valor_pagado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_pagado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(valor_pagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 2, 2, new java.awt.Color(0, 102, 102)));

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setFont(new java.awt.Font("Lucida Console", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("REPORTE DEL PAGO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 430, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image55ef95555423e5_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ConexionSistemaBancario cn = new ConexionSistemaBancario().conectar();
        Connection c=cn.getConexion();
        // Llamada al procedimiento almacenado
        try {
            CallableStatement cst = c.prepareCall("{call PA_INSERTAR_PAGO (?,?,?,?,?,?,?,?,?)}");
            cst.setInt(1, Integer.parseInt(id_pago.getText()));
            cst.setString(2, numero_pres.getText());
            cst.setString(3, numero_pago.getText());
            cst.setString(4, fecha_pago.getText());
            cst.setString(5, capital_inicial.getText());
            cst.setString(6, amortizacion_capital.getText());
            cst.setString(7, interes_mensual.getText());
            cst.setString(8, valor_cuota.getText());
            cst.setString(9, valor_pagado.getText());
            cst.execute();
              
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: " + ex.getMessage());
        } finally {
            try {
                c.close();
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Error: " + ex.getMessage());
            }
                
        }
        
        id_pago.setText("");
        numero_pres.setText("");
        numero_pago.setText("");
        //fecha_pago.setText("");
        capital_inicial.setText("");
        amortizacion_capital.setText("");
        interes_mensual.setText("");
        valor_cuota.setText("");
        valor_pagado.setText("");
        
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        ConexionSistemaBancario f = new ConexionSistemaBancario();
        f.conectar();
        String fecha = null;

        int id = Integer.parseInt(id_pago.getText());
        ResultSet resultado;

        try{
            resultado = f.consultar("SELECT numero_pres, numero_pago, fecha_pago, capital_inicial, amortizacion_capital, interes_mensual, valor_cuota, valor_pago FROM Pago "
                + "WHERE id_pago ='"+id+"'");
            while ( resultado.next() ) {
                
                int numeropres = resultado.getInt("numero_pres");
                int numeropago = resultado.getInt("numero_pago");
                
                fecha=resultado.getString("fecha_pago");
                String dia=fecha.substring(8, 10);
                String mes=fecha.substring(5, 7);
                String anio=fecha.substring(0, 4);
                fecha_pago.setText(dia+"-"+mes+"-"+anio);
                                
                int capitalinicial = resultado.getInt("capital_inicial");
                int amortizacioncapital = resultado.getInt("amortizacion_capital");
                int interesmensual = resultado.getInt("interes_mensual");
                int valorcuota = resultado.getInt("valor_cuota");
                int valorpagado = resultado.getInt("valor_pago");  

                numero_pres.setText(""+numeropres);
                numero_pago.setText(""+numeropago);
                capital_inicial.setText(""+capitalinicial);
                amortizacion_capital.setText(""+amortizacioncapital);
                interes_mensual.setText(""+interesmensual);
                valor_cuota.setText(""+valorcuota);
                valor_pagado.setText(""+valorpagado);
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error de conexion con la base de datos");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        ConexionSistemaBancario f = new ConexionSistemaBancario();
        f.conectar();

        int idpago = Integer.parseInt(id_pago.getText());
        
            f.ejecutar("DELETE FROM Pago WHERE id_pago ='"+idpago+"'");
            
                numero_pres.setText("");
                numero_pago.setText("");
                fecha_pago.setText("");
                capital_inicial.setText("");
                amortizacion_capital.setText("");
                interes_mensual.setText("");
                valor_cuota.setText("");
                valor_pagado.setText("");
                            
        JOptionPane.showMessageDialog(null, "Dato eliminado con éxito!");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoActionPerformed
        ConexionSistemaBancario a = new ConexionSistemaBancario();
        a.conectar();

        ResultSet resultado;
        resultado = a.consultar("DELETE FROM PAGO ");

        id_pago.setText("");
        numero_pres.setText("");
        numero_pago.setText("");
        fecha_pago.setText("");
        capital_inicial.setText("");
        amortizacion_capital.setText("");
        interes_mensual.setText("");
        valor_cuota.setText("");
        valor_pagado.setText("");
              // TODO add your handling code here:
    }//GEN-LAST:event_todoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField amortizacion_capital;
    private javax.swing.JTextField capital_inicial;
    private javax.swing.JTextField fecha_pago;
    private javax.swing.JTextField id_pago;
    private javax.swing.JTextField interes_mensual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numero_pago;
    private javax.swing.JTextField numero_pres;
    private javax.swing.JButton todo;
    private javax.swing.JTextField valor_cuota;
    private javax.swing.JTextField valor_pagado;
    // End of variables declaration//GEN-END:variables
}
