/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa.InterfacesSecundaria;

import static Capa.InterfacesSecundaria.Pago.fecha;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sistema_bancario.ConexionSistemaBancario;

/**
 *
 * @author Javier
 */
public class Prestamo extends javax.swing.JFrame {

    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        setTitle("Prestamo");
        fecha_prestamo.setText(fecha());
        siguiente_pago.setText(fecha());
        numeros(numero_pres);
        Telef(cedula_cliente);
        letras(tipo_prestamo);        
        numeros(monto_prestamo);
        numeros(interes_prestamo);
        numeros(frecuencia_pago_dias);
        numeros(numero_cuotas);
        numeros(saldo_prestamo);
    }
    
     public void numeros (JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if (!Character.isDigit(c)){
                    //getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
     
    public void letras (JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if (Character.isDigit(c)){
                    //getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
     
     private int ct = 10;
    public void Telef (JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if (!Character.isDigit(c)){
                    //getToolkit().beep();
                    e.consume();
                }
                if (a.getText().length()== ct)
                    e.consume();
            }
        });
    }
    
    public static String fecha(){
        Date fecha=new Date();
        SimpleDateFormat formatofecha=new SimpleDateFormat("dd-MM-YYYY");
        return formatofecha.format(fecha);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numero_pres = new javax.swing.JTextField();
        fecha_prestamo = new javax.swing.JTextField();
        siguiente_pago = new javax.swing.JTextField();
        cedula_cliente = new javax.swing.JTextField();
        monto_prestamo = new javax.swing.JTextField();
        frecuencia_pago_dias = new javax.swing.JTextField();
        tipo_prestamo = new javax.swing.JTextField();
        interes_prestamo = new javax.swing.JTextField();
        Limpiar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonIngresar = new javax.swing.JButton();
        numero_cuotas = new javax.swing.JTextField();
        saldo_prestamo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nº de Préstamo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CI Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tipo del Préstamo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Monto del Préstamo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Interes del Préstamo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Fecha del Préstamo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos-para-prestamos_Credixpress-05_opt.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 140, 150));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Frecuencia de Pago:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Siguiente Pago:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nº de la Cuota:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Saldo del Préstamo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 150, 30));

        numero_pres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numero_pres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero_pres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_presActionPerformed(evt);
            }
        });
        getContentPane().add(numero_pres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 60, 30));

        fecha_prestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha_prestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fecha_prestamo.setDisabledTextColor(new java.awt.Color(153, 0, 0));
        fecha_prestamo.setEnabled(false);
        getContentPane().add(fecha_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 95, 140, 20));

        siguiente_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        siguiente_pago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(siguiente_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 95, 140, 20));

        cedula_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cedula_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cedula_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 20));

        monto_prestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monto_prestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(monto_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 20));

        frecuencia_pago_dias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        frecuencia_pago_dias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(frecuencia_pago_dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 160, 20));

        tipo_prestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipo_prestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tipo_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 160, 20));

        interes_prestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        interes_prestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(interes_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 160, 20));

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_opt.png"))); // NOI18N
        Limpiar.setBorder(null);
        Limpiar.setContentAreaFilled(false);
        Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, 60));

        BotonBuscar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar-TuneaTaringa_opt.png"))); // NOI18N
        BotonBuscar.setBorder(null);
        BotonBuscar.setContentAreaFilled(false);
        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 170, 50));

        BotonIngresar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        BotonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardar_opt.png"))); // NOI18N
        BotonIngresar.setToolTipText("");
        BotonIngresar.setBorder(null);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 140, 40));

        numero_cuotas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numero_cuotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(numero_cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, 20));

        saldo_prestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        saldo_prestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(saldo_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 2, 2, new java.awt.Color(0, 102, 102)));

        jLabel13.setBackground(new java.awt.Color(204, 255, 204));
        jLabel13.setFont(new java.awt.Font("Lucida Console", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("REPORTE DEL PRÉSTAMO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 550, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image55ef95555423e5_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        // TODO add your handling code here:       
        
        ConexionSistemaBancario cn=new ConexionSistemaBancario().conectar();            // Conecta con la base de datos XE con el usuario system y la contraseña password
        Connection c=cn.getConexion();
          // Llamada al procedimiento almacenado
        try {
            CallableStatement cst = c.prepareCall("{call PA_INSERTAR_PRESTAMO (?,?,?,?,?,?,?,?,?,?)}");
            cst.setInt(1, Integer.parseInt(numero_pres.getText()));
            cst.setString(2, cedula_cliente.getText());
            cst.setString(3, fecha_prestamo.getText());
            cst.setString(4, tipo_prestamo.getText());
            cst.setString(5, monto_prestamo.getText());
            cst.setString(6, interes_prestamo.getText());
            cst.setString(7, frecuencia_pago_dias.getText());
            cst.setString(8, numero_cuotas.getText());
            cst.setString(9, saldo_prestamo.getText());
            cst.setString(10, siguiente_pago.getText());
            cst.execute();
              
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: " + ex.getMessage());
        } finally {
            try {
                c.close();
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Error: " + ex.getMessage());
            }
                
        }
        
        numero_pres.setText("");
        cedula_cliente.setText("");
        fecha_prestamo.setText("");
        tipo_prestamo.setText("");
        monto_prestamo.setText("");
        interes_prestamo.setText("");
        frecuencia_pago_dias.setText("");
        numero_cuotas.setText("");
        saldo_prestamo.setText("");
        siguiente_pago.setText("");
        

        //JOptionPane.showMessageDialog(null, "La información se guardo con éxito!");
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        ConexionSistemaBancario f = new ConexionSistemaBancario();
        f.conectar();
        String fecha = null;

        int ide = Integer.parseInt(cedula_cliente.getText());
        ResultSet resultado;

        try{
            resultado = f.consultar("SELECT numero_pres, cedula_cliente, fecha_prestamo, tipo_prestamo, monto_prestamo, interes_prestamo, frecuencia_pago_dias, numero_cuotas, saldo_prestamo, siguiente_pago FROM Prestamo "
                 + "WHERE cedula_cliente ='"+ide+"'");
           

            
            while ( resultado.next() ) {
                
                int pago = resultado.getInt("numero_pres");                
                int cedulacliente = resultado.getInt("cedula_cliente");                
                
                fecha=resultado.getString("fecha_prestamo");
                String dia=fecha.substring(8, 10);
                String mes=fecha.substring(5, 7);
                String anio=fecha.substring(0, 4);
                fecha_prestamo.setText(dia+"-"+mes+"-"+anio);
                                                
                String tipoprestamo = resultado.getString("tipo_prestamo");
                String montoprestamo = resultado.getString("monto_prestamo");
                String interesprestamo = resultado.getString("interes_prestamo");
                int frecuenciapagodias = resultado.getInt("frecuencia_pago_dias");
                int numerocuotas = resultado.getInt("numero_cuotas");
                String saldoprestamo = resultado.getString("saldo_prestamo");
                
                fecha=resultado.getString("siguiente_pago");
                dia=fecha.substring(8, 10);
                mes=fecha.substring(5, 7);
                anio=fecha.substring(0, 4);
                siguiente_pago.setText(dia+"-"+mes+"-"+anio);
                
                numero_pres.setText(""+pago);
                cedula_cliente.setText(""+cedulacliente);
                tipo_prestamo.setText(""+tipoprestamo);
                monto_prestamo.setText(""+montoprestamo);
                interes_prestamo.setText(""+interesprestamo);
                frecuencia_pago_dias.setText(""+frecuenciapagodias);
                numero_cuotas.setText(""+numerocuotas);
                saldo_prestamo.setText(""+saldoprestamo);
            }
            
        }
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error de conexion con la base de datos");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        ConexionSistemaBancario f = new ConexionSistemaBancario();
        f.conectar();

        int numeropres = Integer.parseInt(numero_pres.getText());

        f.ejecutar("DELETE FROM Prestamo WHERE numero_pres ='"+numeropres+"'");

        cedula_cliente.setText("");
        fecha_prestamo.setText("");
        tipo_prestamo.setText("");
        monto_prestamo.setText("");
        interes_prestamo.setText("");
        frecuencia_pago_dias.setText("");
        numero_cuotas.setText("");
        saldo_prestamo.setText("");
        siguiente_pago.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void numero_presActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_presActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_presActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField cedula_cliente;
    private javax.swing.JTextField fecha_prestamo;
    private javax.swing.JTextField frecuencia_pago_dias;
    private javax.swing.JTextField interes_prestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monto_prestamo;
    private javax.swing.JTextField numero_cuotas;
    private javax.swing.JTextField numero_pres;
    private javax.swing.JTextField saldo_prestamo;
    private javax.swing.JTextField siguiente_pago;
    private javax.swing.JTextField tipo_prestamo;
    // End of variables declaration//GEN-END:variables
}
